name: "🐞 Bug report / Rapport de bug"
description: "FR/EN — Signaler un bug (champs guidés + obligatoires)"
title: "[BUG] "
labels: ["bug"]
assignees:
  - iMoDzF4N4TiK

body:
  - type: markdown
    attributes:
      value: |
        Merci 🙌  
        **FR/EN :** remplis au minimum une langue (FR ou EN).  
        Astuce : joins un fichier `.knd` / capture / logs si possible.

  - type: dropdown
    id: lang
    attributes:
      label: "Langue / Language"
      options:
        - "Français (FR)"
        - "English (EN)"
        - "Both / Les deux"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version KND-Tool"
      placeholder: "ex: 1.0.1.5"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "OS"
      options:
        - "Windows 11"
        - "Windows 10"
        - "Linux"
        - "macOS"
        - "Other"
    validations:
      required: true

  - type: input
    id: os_details
    attributes:
      label: "OS details (if needed)"
      placeholder: "ex: Windows 11 23H2"
    validations:
      required: false

  - type: dropdown
    id: run_from
    attributes:
      label: "Run from / Lancement"
      options:
        - "Release (.exe)"
        - "Python (.py)"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: action
    attributes:
      label: "Where does it happen? / Où ça bug ?"
      options:
        - "Open .knd"
        - "Export JSON"
        - "Export TXT"
        - "Patch back to .knd"
        - "Diff / Compare"
        - "Backup"
        - "Update checker"
        - "UI / Translation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity / Gravité"
      options:
        - "Crash / Hard crash"
        - "Major (feature broken)"
        - "Minor (annoying)"
        - "Cosmetic (UI only)"
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: "What happened? / Problème"
      description: "Décris clairement le problème."
      placeholder: |
        FR: Quand je fais ..., il se passe ...
        EN: When I do ..., it does ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce / Étapes"
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior / Résultat attendu"
      placeholder: |
        FR: Je m’attendais à ...
        EN: I expected ...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior / Résultat actuel"
      placeholder: |
        FR: À la place ...
        EN: Instead ...
    validations:
      required: true

  - type: dropdown
    id: has_logs
    attributes:
      label: "Logs available? / Logs dispo ?"
      options:
        - "Yes / Oui"
        - "No / Non"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs / Error message"
      render: shell
      placeholder: "Colle ici l’erreur / paste error here"
    validations:
      required: false

  - type: textarea
    id: attachments
    attributes:
      label: "Attachments (optional) / Fichiers (optionnel)"
      description: "Glisse-dépose tes fichiers dans l’issue (captures, .knd, etc.)."
      placeholder: "Screenshots / .knd / video link…"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "J’ai testé avec la dernière release"
          required: true
        - label: "J’ai mis des étapes claires"
          required: true
        - label: "J’ai joint logs/capture si possible"
          required: false


